name: Generate a build and push to katelio.fr (demo)

on:
  push:
    branches:
      - demo

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and Push (demo)
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Install dependencies
        run: npm install

      # Optionnel: si variables d'environnement
      - name: Add environment variables
        run: |
          echo "VITE_KATELIOPWD=${{ secrets.VITE_KATELIOPWD }}" >> $GITHUB_ENV

      - name: Build the project
        run: npm run build

      - name: List dist directory
        run: ls -la dist

      - name: Push to buildDemo branch
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: buildDemo # Le nom de la branche où tu veux pousser les assets
          FOLDER: dist # Le répertoire où tes assets sont générés
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # GitHub l'ajoutera automatiquement - pas besoin de récupérer un token
          MESSAGE: "Build: ({sha}) {msg}" # Le message de commit
